# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc626449558956e58d5e81df4aa18e94894287c91db72a0405b6cff1b09df92ed3bc98ef5e3dacd42c1ed159135f02987c46d2f1033919a7b838c1e71f8cc72d

test:
  secret_key_base: d3cf9650ea92dae08c27a4f8e7eebcb8d7d735f402dbd2e02ff0b97521c9181c0d0004909cc5f884f623d605dad80fc3b21fe19acbeed70d9e3c8e655118cad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
